version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: rest
      MYSQL_PASSWORD: bs123
      MYSQL_ROOT_PASSWORD: bs123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
          - .:/data/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    container_name: bs-rest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
        - db
    ports:
      - "8080:8080"
    volumes:
      - .:/data/roulettebettingsystem
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/test
      - SPRING_DATASOURCE_USERNAME=rest
      - SPRING_DATASOURCE_PASSWORD=bs123
      - SPRING_JPA_HIBERNATE_DDL-AUTO=none
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQL57Dialect
      - SPRING_JPA_GENERATE-DDL=true
      - SPRING_JPA_SHOW-SQL=true

