version: '2.1'
services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: rest
      MYSQL_PASSWORD: bs123
      MYSQL_ROOT_PASSWORD: bs123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306"
    volumes:
          - .:/data/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=rest --password=bs123 --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 10s
      retries: 5

  web:
    container_name: bs-rest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      db:
       condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/data/rouletteadvisorysystem


