version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: rest
      MYSQL_PASSWORD: bs123
      MYSQL_ROOT_PASSWORD: bs123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306"
    volumes:
          - .:/data/mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    container_name: bs-rest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
        - db
    ports:
      - "8080:8080"
    volumes:
      - .:/data/roulettebettingsystem

