version: '3'
services:
  bs-mysql:
    container_name: bs-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: bs123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - bs-mysql